### ISSUE TITLE
How to use with local ollama?

### ISSUE THREAD

**Issue by farzadmf** [Storia-AI/repo2vec#32]
Hi, I tried to follow the steps in the README, trying to use `ollama`.

First of all, it mentions in the README to do `r2v-index $repo`, but seems like `--index-name` is required as well, so maybe worth updating the instructions.

Secondly, doing `r2v-index $repo --index-name myindex`, it's giving the error:
```
r2v-index: error: Please set the OPENAI_API_KEY environment variable.
```

It's probably some instruction/flag missing from the README

**Comment by iuliaturc** [comment]
Thanks for your question!

Here are the relevant bits from the readme:
(1) Preprequisites
<img width="881" alt="Screenshot 2024-09-08 at 10 07 52 AM" src="https://github.com/user-attachments/assets/bbe38209-99a2-4fd1-b2d8-04807f513613">

(2) How to run it
<img width="911" alt="Screenshot 2024-09-08 at 10 08 17 AM" src="https://github.com/user-attachments/assets/49bc3181-7983-4b67-b8a0-9b13a86405e8">


We defaulted local usage under a toggle that is closed by default, that why it probably wasn't obvious to you. I wanted to minimize the information overload, but maybe it's better to have it open so that people can just ctrl+F.

**Comment by iuliaturc** [comment]
Also, could you please make sure you're using the latest version `0.1.7`? Just pushed a new one to pypi.

**Comment by farzadmf** [comment]
Thank you @iuliaturc for your reply. Yes, upgrading to `0.1.7` seems to solve the issue.

Although I must say that for a large repo, everything is very slow and not _super_ helpful, but it very well be because of the model I'm using (`llama3.1:latest`) and possibly because my system is not powerful enough.

I think I can close this issue since my original issue is solved; the slowness etc. I guess could be considered as "features"

**Comment by iuliaturc** [comment]
Thanks for the feedback!

Indeed, OpenAI embeddings are much better than OSS at this point.
And if you don't have a GPU installed, building them locally will also be slower.

We have a whole roadmap in front of us to make things better, thanks for giving it a go.
